# Generated by Django 4.0.5 on 2022-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='subject',
            field=models.CharField(default='Flower pot', max_length=100),
            preserve_default=False,
        ),
    ]
