# Generated by Django 4.0.5 on 2022-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='htmlfile',
            name='content',
        ),
        migrations.AddField(
            model_name='htmlfile',
            name='file',
            field=models.FileField(default=1, upload_to='files/'),
            preserve_default=False,
        ),
    ]
